version: '3.9'

services:
  api:
    build: .
    container_name: cordipdf-api
    env_file: .env
    environment:
      - PORT=${PORT:-3000}
      - MONGO_HOST=${MONGO_HOST:-mongo}
      - MONGO_PORT=${MONGO_PORT:-27017}
      - MONGO_DB=${MONGO_DB:-miapp}
      - MONGO_URI=${MONGO_URI:-mongodb://${MONGO_HOST:-mongo}:${MONGO_PORT:-27017}/${MONGO_DB:-miapp}}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7.0
    container_name: cordipdf-mongo
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27017}:${MONGO_PORT:-27017}"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
