version: '3.9'

services:
  api:
    build: .
    container_name: cordipdf-api
    env_file: .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - MONGO_HOST=${MONGO_HOST:-mongo}
      - MONGO_PORT=${MONGO_PORT:-23023}
      - MONGO_DB=${MONGO_DB:-cordipdf-bda}
      - MONGO_URI=mongodb://${MONGO_HOST:-mongo}:${MONGO_PORT:-23023}/${MONGO_DB:-cordipdf-bda}
      - MONGO_EXPRESS_PORT=${MONGO_EXPRESS_PORT:-8081}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: ${MONGO_IMAGE:-mongo:8.0}
    container_name: cordipdf-mongo
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-23023}:${MONGO_PORT:-23023}"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
